# "org" ensures this Service is used with the correct Serverless Framework Access Key.
# org: tomtucker
# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: vin-webhook # NOTE: update this with your service name
app: vin-webhook-receiver
#tenant: your-tenant-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"
configValidationMode: error

provider:
  name: aws
  runtime: python3.9
  #lambdaHashingVersion: 20201221 

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

# you can add statements to the Lambda function's IAM Role here
  iam:
    role:
      statements:
      - Effect: "Allow"
        Action:
        - "s3:*"
        Resource: { "Fn::Join": ["", ["arn:aws:s3:::vin.eventmanager", "/*" ] ] }

# you can define service wide environment variables here
#  environment:
#    variable1: value1
  environment:
    debug: 0
    api_env: Staging
    api_base: 'https://api.staging.vindicia.com'
    api_version: '27.0'
    api_key: '<api_user>:<api_password>'
    hmac_key: '<secret_hmac_key>'
    region: 'us-east-1'
    s3bucket: '<s3-bucket-name>'

# Packaging information here
package:
  individually: true
#  include:
#    - include-me.py
#    - include-me-dir/**
#  exclude:
#    - exclude-me.py
#    - exclude-me-dir/**
  patterns:
    - '!.venv/**'
    - '!.vscode/**'
    - '!node_modules/**'
    - '!__pycache__/**'
    - '!test/**'
    - '!tmp/**'
    - '!.project'
    - '!.pydevproject'
    - '!.python-version'
    - '!package-lock.json'
    - '!package.json'
    - '!template.yml'
    - '!serverless-*.yml'
    

functions:
  receiver:
    handler: handler.vin_event
#    The following are a few example events you can configure
#    NOTE: Please make sure to change your handler code to work with those events
#    Check the event documentation for details
    events:
      - http:
         path: event_manager
         method: post

plugins:
  - serverless-python-requirements
  - serverless-plugin-optimize
  - serverless-s3-local
custom:
  pythonRequirements:
    dockerizePip: true
  enable_optimize:
    local: false
